### ISSUE TITLE
New API

### ISSUE THREAD

**Issue by grassator** [zalando-incubator/perron#67]
Perron started to solve a very particular problem. Internal usage in moderately high load service and attempts to use it in more scenarios showed some design flaws, namely:

* Library has quite a high barrier of entry and is not easy to use for common cases
* No streaming support
* Host-oriented nature of it feels clunky at times (e.g. when interacting with GraphQL endpoints) both around circuit breaker and filters.
* Current circuit breaker library has several deficiencies of its own but it is very hard to change to something else because we expose the API directly. Here are some examples:
  * unnecessary garbage
  * non-derefed timers
  * clunky interface
* Since TypeScript was kind of bolted on top of the library, the types are problematic in many places:
  * because of how TypeScript handles exceptions, there is no way to make sure all the error types are handled by client code
  * it would be impossible to do type-safe filters that do arbitrary transformations of the response.
* There are issues debugging issues can be hard as not enough response details propagation is happening
* Testing and mocking responses is awkward at times
* Performance can always be better

The proposal is to move to a more traditional fluent API and move core functionality to filters as well:

```js
const { serviceClient, treat5xxAsErrors, circuitBreaker, jsonRequest, jsonResponse retry } = require("perron");

const circuitBreakerByHostname= circuitBreaker({ poolBy: (request) => request.hostname });
const retryTwice = retry({ count: 2})

const exampleClient = serviceClient("https://myapi.example.com/")
  .filter(jsonRequest)
  .filter(treat5xxAsErrors)
  .filter(circuitBreakerByHostname)
  .filter(retryTwice)
  .filter(jsonResponse)

const result = exampleClient
  .request({ foo: "bar" })
  .then(result => {
    // TBD
  })
```

The part I haven't figured out yet is around result. One way would be to use discriminated union types, but this might clunky to use as well.

**Comment by grassator** [comment]
@DeTeam @mo-gr @shuhei would appreciate any thoughts you have including any of the issues I might have forgotten

**Comment by shuhei** [comment]
Thanks for starting a great initiative! Since many things are already covered, here are my two cents.

- A sane way for sharing a context in request filter and response filter
  - For example, to measure response time in a filter, we need to get the current time in the request filter and use it in the response filter. Currently we can associate values to `ServiceClientRequestOptions` by adding extra fields or keeping them in a `WeakMap`, and take them out via `response.request`. It feels a bit hacky to me.
- Treat 4xx as errors but detour circuit breaker
  - I believe this is a very common use case, but currently cannot be supported only with filters.
- Another problem of the circuit breaker: `onCircuitOpen` is called multiple times

**Comment by grassator** [comment]
@shuhei regarding the context, I'm thinking that a decent way might be just have a map (or a pair of functions) that are passed around each filter. Then filters can use Symbols for things that they do not want to share and plain strings for things they do. What do you think?

**Comment by grassator** [comment]
Probably not going to happen in near future so closing for housekeeping reasons.
